services:
  # Backend API (FastAPI)
  - type: web
    name: ninebox-api
    runtime: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PIP_NO_CACHE_DIR
        value: "1"
    healthCheckPath: /api/health

  # Frontend (Arquivos estáticos)
  - type: web
    name: ninebox-frontend
    runtime: static
    plan: free
    buildCommand: echo "No build needed for static files"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
      - path: /*.css
        name: Cache-Control
        value: public, max-age=31536000
      - path: /*.js
        name: Cache-Control
        value: public, max-age=31536000
      - path: /*.jpeg
      - path: /*.jpg
      - path: /*.png
      - path: /*.svg
        name: Cache-Control
        value: public, max-age=31536000
